[package]
name = "testuv"
version = "0.1.0"
edition = "2021"

[dependencies]
ecdsa = "0.16.9"
elliptic-curve = "0.13.8"
hex = "0.4.3"
hex-literal = "0.4.1"
k256 = "0.13.4"
rfc6979 = "0.4.0"
sha2 = "0.10.8"
